In [1]:
import pandas as pd

In [2]:
all_time_df = pd.read_csv(r"C:\Users\K.Asus\Desktop\programing\Data_Analysis\TEST\داتاSpotify\archive\spotify_alltime_top100_songs.csv")
artists_df = pd.read_csv(r"C:\Users\K.Asus\Desktop\programing\Data_Analysis\TEST\داتاSpotify\archive\spotify_wrapped_2025_top50_artists.csv")
songs_2025_df = pd.read_csv(r"C:\Users\K.Asus\Desktop\programing\Data_Analysis\TEST\داتاSpotify\archive\spotify_wrapped_2025_top50_songs.csv")

In [4]:
##تنظيف الو ملف اكثر  اغنيه استماعا 
all_time_df.head()

,alltime_rank,song_title,artist,total_streams_billions,primary_genre,bpm,release_year,artist_country,explicit,danceability,energy,valence,acousticness,dataset_part
0,1,Blinding Lights,The Weeknd,5.26,Synth-Pop,171,2019,Canada,False,0.51,0.80,0.33,0.00,Spotify All-Time Most Streamed Top 100
1,2,Shape of You,Ed Sheeran,4.90,Pop/Dancehall,96,2017,UK,False,0.83,0.65,0.93,0.08,Spotify All-Time Most Streamed Top 100
2,3,Someone You Loved,Lewis Capaldi,4.05,Pop,77,2018,UK,False,0.60,0.45,0.42,0.29,Spotify All-Time Most Streamed Top 100
3,4,Sunflower,Post Malone & Swae Lee,3.98,Hip-Hop/Pop,93,2018,USA,False,0.76,0.49,0.84,0.15,Spotify All-Time Most Streamed Top 100
4,5,One Dance,Drake,3.92,Afrobeats/Pop,100,2016,Canada,False,0.79,0.62,0.68,0.09,Spotify All-Time Most Streamed Top 100

In [5]:
all_time_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   alltime_rank            100 non-null    int64
 1   song_title              100 non-null    object
 2   artist                  100 non-null    object
 3   total_streams_billions  100 non-null    float64
 4   primary_genre           100 non-null    object
 5   bpm                     100 non-null    int64
 6   release_year            100 non-null    int64
 7   artist_country          100 non-null    object
 8   explicit                100 non-null    bool
 9   danceability            100 non-null    float64
 10  energy                  100 non-null    float64
 11  valence                 100 non-null    float64
 12  acousticness            100 non-null    float64
 13  dataset_part            100 non-null    object
dtypes: bool(1), float64(5), int64(3), object(5)
memory usage: 10.4+ KB

In [6]:
# 1. إزالة أي صفوف مكررة بناءً على اسم الأغنية والفنان
all_time_df.drop_duplicates(subset=['song_title', 'artist'], inplace=True)

# 2. التعامل مع القيم المفقودة (Nulls)
# لو في قيم مفقودة في الأعمدة الرقمية ممكن نعوضها بـ 0 أو المتوسط
all_time_df['total_streams_billions'] = all_time_df['total_streams_billions'].fillna(0)

# 3. التأكد من نوع البيانات
all_time_df['release_year'] = all_time_df['release_year'].astype(int)

print("تم تنظيف ملف الأكثر استماعاً بنجاح.")

تم تنظيف ملف الأكثر استماعاً بنجاح.

In [8]:
##تتنظيف الملف الثاني افضل50 فنان لسنه2025 
artists_df.head()

,wrapped_2025_rank,artist_name,monthly_listeners_millions_mar2026,primary_genre,country,followers_millions,grammy_wins,debut_year,gender,top_2025_song,dataset_part
0,1,The Weeknd,110.4,R&B/Pop,Canada,112,4,2010,Male,Die With A Smile,Spotify Wrapped 2025 Top 50 Artists
1,2,Taylor Swift,107.5,Pop/Country,USA,110,14,2006,Female,Fortnight,Spotify Wrapped 2025 Top 50 Artists
2,3,Drake,88.6,Hip-Hop,Canada,95,4,2006,Male,Amen,Spotify Wrapped 2025 Top 50 Artists
3,4,Bad Bunny,84.2,Reggaeton,Puerto Rico,89,0,2016,Male,NUEVAYoL,Spotify Wrapped 2025 Top 50 Artists
4,5,Sabrina Carpenter,82.1,Pop,USA,58,0,2015,Female,Espresso,Spotify Wrapped 2025 Top 50 Artists

In [9]:
artists_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   wrapped_2025_rank                   50 non-null     int64
 1   artist_name                         50 non-null     object
 2   monthly_listeners_millions_mar2026  50 non-null     float64
 3   primary_genre                       50 non-null     object
 4   country                             50 non-null     object
 5   followers_millions                  50 non-null     int64
 6   grammy_wins                         50 non-null     int64
 7   debut_year                          50 non-null     int64
 8   gender                              50 non-null     object
 9   top_2025_song                       50 non-null     object
 10  dataset_part                        50 non-null     object
dtypes: float64(1), int64(4), object(6)
memory usage: 4.4+ KB

In [18]:
##توحيد حالة الحروف وتنسيق النصوص (إزالة المسافات الزائدة)
artists_df['artist_name'] = artists_df['artist_name'].str.strip()
artists_df['primary_genre'] = artists_df['primary_genre'].str.title()

#  التأكد من أن قيم "جوائز غرامي" أرقام صحيحة
artists_df['grammy_wins'] = artists_df['grammy_wins'].fillna(0).astype(int)
print("تم تنظيف ملف اكثر 50 فنان لسنه 2025.")

تم تنظيف ملف اكثر 50 فنان لسنه 2025.

In [14]:
##تنظيف ملف اكثر 50 اغنيه استماع لسنه 2025
songs_2025_df.head()

,wrapped_2025_rank,song_title,artist,streams_2025_billions,primary_genre,bpm,duration_seconds,release_year,artist_country,explicit,danceability,energy,valence,acousticness,peak_global_chart_position,dataset_part
0,1,Die With A Smile,Lady Gaga & Bruno Mars,1.70,Pop,120,251,2024,USA,False,0.72,0.68,0.55,0.18,1,Spotify Wrapped 2025 Top 50 Global Songs
1,2,APT.,ROSE & Bruno Mars,1.62,K-Pop/Pop,145,173,2024,South Korea,False,0.86,0.79,0.88,0.05,1,Spotify Wrapped 2025 Top 50 Global Songs
2,3,Espresso,Sabrina Carpenter,1.55,Pop,104,175,2024,USA,False,0.80,0.73,0.96,0.06,1,Spotify Wrapped 2025 Top 50 Global Songs
3,4,Please Please Please,Sabrina Carpenter,1.48,Pop,107,186,2024,USA,False,0.70,0.66,0.87,0.10,1,Spotify Wrapped 2025 Top 50 Global Songs
4,5,Taste,Sabrina Carpenter,1.41,Pop,117,177,2024,USA,True,0.78,0.70,0.82,0.08,1,Spotify Wrapped 2025 Top 50 Global Songs

In [16]:
songs_2025_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   wrapped_2025_rank           50 non-null     int64
 1   song_title                  50 non-null     object
 2   artist                      50 non-null     object
 3   streams_2025_billions       50 non-null     float64
 4   primary_genre               50 non-null     object
 5   bpm                         50 non-null     int64
 6   duration_seconds            50 non-null     int64
 7   release_year                50 non-null     int64
 8   artist_country              50 non-null     object
 9   explicit                    50 non-null     bool
 10  danceability                50 non-null     float64
 11  energy                      50 non-null     float64
 12  valence                     50 non-null     float64
 13  acousticness                50 non-null     float64
 14  peak_global_chart_position  50 non-null     int64
 15  dataset_part                50 non-null     object
dtypes: bool(1), float64(5), int64(5), object(5)
memory usage: 6.0+ KB

In [17]:
# 1. تحويل المدة من ثواني إلى دقائق (اختياري لتحسين القراءة)
songs_2025_df['duration_min'] = songs_2025_df['duration_seconds'] / 60

# 2. التعامل مع القيم المنطقية (Boolean)
# التأكد من أن عمود 'explicit' معالج بشكل صحيح
songs_2025_df['explicit'] = songs_2025_df['explicit'].astype(bool)

# 3. التحقق من القيم المتطرفة (Outliers) في الـ BPM
# مثلاً التأكد أن مفيش أغنية الـ BPM بتاعها صفر
songs_2025_df = songs_2025_df[songs_2025_df['bpm'] > 0]

print("تم تنظيف ملف أغاني 2025 بنجاح.")

تم تنظيف ملف أغاني 2025 بنجاح.

In [19]:
all_time_df.to_csv(r"C:\Users\K.Asus\Desktop\programing\Data_Analysis\TEST\داتاSpotify\archive\top100_clean.csv", index=False, encoding='utf-8-sig')
artists_df.to_csv(r"C:\Users\K.Asus\Desktop\programing\Data_Analysis\TEST\داتاSpotify\archive\top50_artists_clean.csv", index=False, encoding='utf-8-sig')
songs_2025_df.to_csv(r"C:\Users\K.Asus\Desktop\programing\Data_Analysis\TEST\داتاSpotify\archive\top50_songs_clean.csv", index=False, encoding='utf-8-sig')
print("الملفات كلها وصلت يا معلم ")

الملفات كلها وصلت يا معلم